[package]
name = "etui"
version = "0.1.0"
edition = "2021"
authors = ["Parker TenBroeck"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26"
unicode-width = "0.1"